// Marginalia kind glyphs: drawn as clean paths on a 24px grid, then given a pen-sketch line with rough.js
// (fixed seeds, so the drawings are stable). Output: src/sketch.ts (inner SVG markup per kind).
import { createRequire } from 'node:module';
const rough = createRequire(import.meta.url)('roughjs/bundled/rough.cjs.js');
import { writeFileSync } from 'node:fs';

const gen = rough.generator();
const base = { roughness: 0.85, bowing: 1.3, strokeWidth: 1, disableMultiStroke: true, preserveVertices: true, curveFitting: 0.96 };

// each kind: list of [shape, args, extra opts]; 'dot' = a filled circle drawn clean (rough dots get muddy at 16px)
const K = {
  game: [
    ['path', 'M7.2 7.2h9.6a4.4 4.4 0 0 1 4.3 3.5l.95 4.8a2.9 2.9 0 0 1-5 2.5l-1.6-1.8H8.55l-1.6 1.8a2.9 2.9 0 0 1-5-2.5l.95-4.8a4.4 4.4 0 0 1 4.3-3.5z'],
    ['path', 'M7.2 10.4v4.2M5.1 12.5h4.2'],
    ['dot', 16.1, 11.2, 0.95], ['dot', 18.1, 13.4, 0.95],
  ],
  music: [
    ['path', 'M13.6 4.5C18.6 4.5 22.1 7.8 22.1 12S18.6 19.5 13.6 19.5'], // the record, sliding out of its sleeve
    ['path', 'M13.6 9.7C15.4 9.7 16.8 10.7 16.8 12S15.4 14.3 13.6 14.3'],  // its label
    ['dot', 14.7, 12, 0.6],                                                // the spindle hole
    ['path', 'M3 4.2h10.6v15.6H3z'],                            // the sleeve
    ['path', 'M5.6 8.2h5.2M5.6 10.9h3.2'],                      // the sleeve's label
  ],
  film: [
    ['path', 'M3.6 10.2h16.8v9.6H3.6z'],                        // the slate
    ['path', 'M3.6 10.2 3.1 6.6l16.6-2.5.6 3.6'],                // the clapper, lifted
    ['path', 'M7.4 9.6l-.9-3.5M11.6 9l-.9-3.6M15.8 8.4l-.9-3.6'], // stripes
    ['path', 'M6.4 14.2h6.6M6.4 16.9h4'],
  ],
  book: [
    ['path', 'M6.3 3.6h11.4v16.8H6.3z'],
    ['path', 'M8.8 3.6v16.8'],
    ['path', 'M14.4 20.4v2.6l1.1-1 1.1 1v-2.6'],                // ribbon
    ['path', 'M11.2 8h4M11.2 10.4h2.6'],
  ],
  manga: [
    ['path', 'M4.2 3.4h15.6v17.2H4.2z'],
    ['path', 'M4.2 11.2h15.6M12.6 3.4v7.8M9.2 11.2v9.4'],
    ['path', 'M6.4 6.4c0-1.1 1-1.8 2.2-1.8s2.2.7 2.2 1.8-1 1.8-2.2 1.8c-.4 0-.8 0-1.1-.2l-1.1.7.3-1.1c-.2-.3-.3-.7-.3-1.2z'],
  ],
  anime: [
    ['path', 'M3.2 8.2h17.6v11.6H3.2z'],
    ['path', 'M8.6 4.2l3.4 4 3.4-4'],
    ['path', 'M12 10.8l.75 2.25 2.25.75-2.25.75L12 16.8l-.75-2.25-2.25-.75 2.25-.75z'],
  ],
  series: [
    ['path', 'M7.4 4.4h13v9.6'],                                 // the next episode behind
    ['path', 'M3.6 7.6h13.6v11.6H3.6z'],
    ['path', 'M8.6 11.2v4.4l3.6-2.2z'],
  ],
  poem: [
    ['path', 'M19.8 3.6c-6.4.6-10.6 5.6-11.6 12'],
    ['path', 'M19.8 3.6c.2 5.6-4.4 10.8-11.6 12'],
    ['path', 'M8.2 15.6 4 20.4'],
    ['path', 'M15.6 7l-3.4 5.2'],
  ],
  story: [
    ['path', 'M6 20.6V10.6h12v10'],
    ['path', 'M6 10.6V7.4h2.1V9h1.9V7.4h4V9h1.9V7.4H18v3.2'],
    ['path', 'M10.2 20.6v-3.4a1.8 1.8 0 0 1 3.6 0v3.4'],
    ['path', 'M12 7.4V3.4l3.1 1.1L12 5.6'],
    ['path', 'M3.6 20.6h16.8'],
  ],
};
const SEEDS = { game: 11, music: 23, film: 37, book: 41, manga: 53, anime: 67, series: 71, poem: 83, story: 97 };

const r2 = (n) => Math.round(n * 100) / 100;
const tidy = (d) => d.replace(/-?\d+\.\d+/g, (m) => String(r2(parseFloat(m))));
const outTs = ['// Marginalia kind glyphs — drawn on a 24px grid, pen-sketched with rough.js 4.6.6 (MIT) at build time. Generated by gen_sketch.mjs.',
  'export const SKETCH: Record<string, string> = {'];
const svgs = {};
for (const [kind, parts] of Object.entries(K)) {
  let i = 0, markup = '';
  for (const [shape, ...args] of parts) {
    if (shape === 'dot') { const [x, y, r] = args; markup += `<circle cx="${x}" cy="${y}" r="${r}" fill="currentColor" stroke="none"/>`; continue; }
    const drawable = gen.path(args[0], { ...base, seed: SEEDS[kind] * 10 + i++ });
    for (const p of gen.toPaths(drawable)) markup += `<path d="${tidy(p.d)}"/>`;
  }
  svgs[kind] = markup;
  outTs.push(`  ${kind}: '${markup}',`);
}
outTs.push('};', '');
// empty states: three small drawings on a 120 × 72 grid, the same pen
const E = {
  shelf: [  // an empty shelf: two bookends, and a ribbon someone left behind
    ['path', 'M8 56h104M10 61.5h100'], ['path', 'M30 56V30.5h2.6V56'], ['path', 'M30 56h11'], ['path', 'M90 56V30.5h-2.6V56'], ['path', 'M90 56H79'],
    ['path', 'M50 55.4c3.4-3.2 7-3.2 10.4 0s7 3.2 10.4 0'],
  ],
  journal: [  // a journal open at its first page: two lines, then nothing yet
    ['path', 'M60 19C48 13.5 30 13.5 15 17.5v39c15-4 33-4 45 2'], ['path', 'M60 19c12-5.5 30-5.5 45-1.5v39c-15-4-33-4-45 2'], ['path', 'M60 19v39.5'],
    ['path', 'M23 27.5c9-1.6 18-1.6 28 0M23 34c7-1.2 13-1.2 19 0'],
  ],
  find: [  // a page under the glass, and nothing on it
    ['path', 'M28 11h34l8 8v42H28z'], ['path', 'M62 11v8h8'], ['path', 'M35 23h20M35 30h14'],
    ['path', 'M84 41a12 12 0 1 1-24 0a12 12 0 0 1 24 0'], ['path', 'M66 36a7 7 0 0 1 6-4'], ['path', 'M80.6 49.6l11.5 11.5'],
  ],
};
outTs.push('// empty-state drawings, viewBox 0 0 120 72', 'export const EMPTY: Record<string, string> = {');
const ESEED = { shelf: 131, journal: 137, find: 139 }, esvgs = {};
for (const [name, parts] of Object.entries(E)) {
  let i = 0, markup = '';
  for (const [, d] of parts) for (const p of gen.toPaths(gen.path(d, { ...base, roughness: 0.9, seed: ESEED[name] * 10 + i++ }))) markup += `<path d="${tidy(p.d)}"/>`;
  esvgs[name] = markup; outTs.push(`  ${name}: '${markup}',`);
}
outTs.push('};', '');
writeFileSync('src/sketch.ts', outTs.join('\n'));
// a review sheet
const cell = (k, size, sw) => `<div style="display:grid;justify-items:center;gap:6px"><svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="#2b2018" stroke-width="${sw}" stroke-linecap="round" stroke-linejoin="round">${svgs[k]}</svg><span style="font:11px system-ui;color:#5e4f44">${k}</span></div>`;
const row = (size, sw) => `<div style="display:flex;gap:26px;margin:0 0 18px">${Object.keys(K).map((k) => cell(k, size, sw)).join('')}</div>`;
writeFileSync('test/sketch.html', `<!doctype html><body style="margin:0;padding:24px;background:#f8f2e9">${row(64, 1.5)}${row(24, 1.75)}${row(16, 2)}</body>`);
console.log('kinds:', Object.keys(svgs).length, 'empty:', Object.keys(esvgs).length);
