"""Bookcloth: 12 families x 3 tones in OKLCH. Core 24 = deep + true; extended 12 = dusty."""
import json, itertools
from coloraide import Color

FAM = [  # (family, hue, deep, true, dusty)
  ("red",      20,  "Oxblood",   "Madder",    "Rosewood"),
  ("rust",     46,  "Conker",    "Rust",      "Terracotta"),
  ("ochre",    78,  "Tobacco",   "Ochre",     "Buckram"),
  ("olive",   108,  "Loden",     "Olive",     "Lichen"),
  ("green",   145,  "Forest",    "Fern",      "Sage"),
  ("bottle",  172,  "Bottle",    "Jade",      "Celadon"),
  ("teal",    202,  "Spruce",    "Teal",      "Verdigris"),
  ("petrol",  232,  "Prussian",  "Petrol",    "Pewter"),
  ("indigo",  268,  "Navy",      "Indigo",    "Woad"),
  ("violet",  305,  "Aubergine", "Amethyst",  "Heather"),
  ("mulberry",345,  "Mulberry",  "Raspberry", "Mauve"),
  ("neutral",  None, "Charcoal",  "Umber",     "Ash"),
]
TONE = {"deep": (0.335, 0.085), "true": (0.43, 0.125), "dusty": (0.47, 0.06)}
DUSTY_L = [0.445, 0.495]  # alternate by family so neighbours differ in lightness too
NEUTRAL = {"deep": (0.315, 0.018, 255), "true": (0.40, 0.045, 55), "dusty": (0.47, 0.02, 75)}
GILT = "#efe0bc"

def hexof(L, C, H):
    c = Color("oklch", [L, C, H]).convert("srgb")
    if not c.in_gamut(): c = c.fit("srgb", method="oklch-chroma")
    return c.to_string(hex=True)

out = []
for fam, h, *names in FAM:
    for tone, name in zip(["deep", "true", "dusty"], names):
        if h is None: L, C, H = NEUTRAL[tone]
        else:
            (L, C), H = TONE[tone], h
            if tone == "dusty": L = {"teal": 0.478}.get(fam, DUSTY_L[[f[0] for f in FAM].index(fam) % 2])
            if tone == "true": L = {"teal": 0.40}.get(fam, L)
        hx = hexof(L, C, H)
        out.append({"id": name.lower(), "name": name, "family": fam, "tone": tone, "core": tone != "dusty", "hex": hx})

bad = []
for c in out:
    cr = Color(GILT).contrast(Color(c["hex"]), method="wcag21")
    c["gilt"] = round(cr, 2)
    if cr < 4.5: bad.append((c["name"], cr))
pairs = []
for a, b in itertools.combinations(out, 2):
    d = Color(a["hex"]).delta_e(Color(b["hex"]), method="ok")
    pairs.append((round(d, 3), a["name"], b["name"]))
pairs.sort()
print("gilt fails:", bad)
print("closest pairs (ΔE OK):", pairs[:8])
json.dump(out, open("cloth.json", "w"), indent=1)
for c in out: print(f'{c["name"]:10s} {c["family"]:8s} {c["tone"]:5s} {c["hex"]} gilt {c["gilt"]}')

# ── write src/cloth.ts
order = [c for c in out if c["core"]] + [c for c in out if not c["core"]]
ts = ["// Marginalia bookcloth — generated by cloth/make_cloth.py. 12 families x 3 tones; core 24 = deep + true, extended 12 = dusty.",
      "import { toOklch } from './ink';",
      "export interface Cloth { id: string; name: string; family: string; tone: 'deep' | 'true' | 'dusty'; core: boolean; hex: string }",
      "export const CLOTHS: Cloth[] = ["]
for c in out:
    ts.append(f"  {{ id: '{c['id']}', name: '{c['name']}', family: '{c['family']}', tone: '{c['tone']}', core: {str(c['core']).lower()}, hex: '{c['hex']}' }},")
ts += ["];",
"export const CORE_24 = CLOTHS.filter((c) => c.core);",
"export const clothById = (id: string) => CLOTHS.find((c) => c.id === id);",
"/** Snap any colour (a sampled cover) to the nearest bookcloth, so every entry's ink comes from the curated set. */",
"export function nearestCloth(hex: string, set: Cloth[] = CLOTHS): Cloth {",
"  const lab = (h: string) => { const [L, C, H] = toOklch(h); const r = (H * Math.PI) / 180; return [L, C * Math.cos(r), C * Math.sin(r)]; };",
"  const [l0, a0, b0] = lab(hex);",
"  // compare hue and chroma, not lightness: a pale cover and a dark cover of the same hue map to the same family",
"  let best = set[0], bd = Infinity;",
"  for (const c of set) { const [l, a, b] = lab(c.hex); const d = (a - a0) ** 2 + (b - b0) ** 2 + 0.02 * (l - l0) ** 2; if (d < bd) { bd = d; best = c; } }",
"  return best;",
"}",
"/** No art and no pick: a stable cloth from the core 24, chosen by the title. */",
"export function autoCloth(title: string): Cloth {",
"  let h = 2166136261; for (let i = 0; i < title.length; i++) { h ^= title.charCodeAt(i); h = Math.imul(h, 16777619); }",
"  return CORE_24[(h >>> 0) % CORE_24.length];",
"}", ""]
open("../src/cloth.ts", "w").write("\n".join(ts))
print("wrote src/cloth.ts")
