// Marginalia bookcloth — generated by cloth/make_cloth.py. 12 families x 3 tones; core 24 = deep + true, extended 12 = dusty.
import { toOklch } from './ink';
export interface Cloth { id: string; name: string; family: string; tone: 'deep' | 'true' | 'dusty'; core: boolean; hex: string }
export const CLOTHS: Cloth[] = [
  { id: 'oxblood', name: 'Oxblood', family: 'red', tone: 'deep', core: true, hex: '#5b2124' },
  { id: 'madder', name: 'Madder', family: 'red', tone: 'true', core: true, hex: '#872b32' },
  { id: 'rosewood', name: 'Rosewood', family: 'red', tone: 'dusty', core: false, hex: '#724646' },
  { id: 'conker', name: 'Conker', family: 'rust', tone: 'deep', core: true, hex: '#592609' },
  { id: 'rust', name: 'Rust', family: 'rust', tone: 'true', core: true, hex: '#843300' },
  { id: 'terracotta', name: 'Terracotta', family: 'rust', tone: 'dusty', core: false, hex: '#7f5745' },
  { id: 'tobacco', name: 'Tobacco', family: 'ochre', tone: 'deep', core: true, hex: '#4e2f00' },
  { id: 'ochre', name: 'Ochre', family: 'ochre', tone: 'true', core: true, hex: '#704600' },
  { id: 'buckram', name: 'Buckram', family: 'ochre', tone: 'dusty', core: false, hex: '#66502c' },
  { id: 'loden', name: 'Loden', family: 'olive', tone: 'deep', core: true, hex: '#3b3900' },
  { id: 'olive', name: 'Olive', family: 'olive', tone: 'true', core: true, hex: '#575300' },
  { id: 'lichen', name: 'Lichen', family: 'olive', tone: 'dusty', core: false, hex: '#65653b' },
  { id: 'forest', name: 'Forest', family: 'green', tone: 'deep', core: true, hex: '#144218' },
  { id: 'fern', name: 'Fern', family: 'green', tone: 'true', core: true, hex: '#11601d' },
  { id: 'sage', name: 'Sage', family: 'green', tone: 'dusty', core: false, hex: '#3e5d3f' },
  { id: 'bottle', name: 'Bottle', family: 'bottle', tone: 'deep', core: true, hex: '#004432' },
  { id: 'jade', name: 'Jade', family: 'bottle', tone: 'true', core: true, hex: '#006149' },
  { id: 'celadon', name: 'Celadon', family: 'bottle', tone: 'dusty', core: false, hex: '#3b6d5e' },
  { id: 'spruce', name: 'Spruce', family: 'teal', tone: 'deep', core: true, hex: '#004147' },
  { id: 'teal', name: 'Teal', family: 'teal', tone: 'true', core: true, hex: '#00555c' },
  { id: 'verdigris', name: 'Verdigris', family: 'teal', tone: 'dusty', core: false, hex: '#2e676b' },
  { id: 'prussian', name: 'Prussian', family: 'petrol', tone: 'deep', core: true, hex: '#003d5a' },
  { id: 'petrol', name: 'Petrol', family: 'petrol', tone: 'true', core: true, hex: '#005882' },
  { id: 'pewter', name: 'Pewter', family: 'petrol', tone: 'dusty', core: false, hex: '#3c687e' },
  { id: 'navy', name: 'Navy', family: 'indigo', tone: 'deep', core: true, hex: '#243362' },
  { id: 'indigo', name: 'Indigo', family: 'indigo', tone: 'true', core: true, hex: '#334994' },
  { id: 'woad', name: 'Woad', family: 'indigo', tone: 'dusty', core: false, hex: '#465376' },
  { id: 'aubergine', name: 'Aubergine', family: 'violet', tone: 'deep', core: true, hex: '#412959' },
  { id: 'amethyst', name: 'Amethyst', family: 'violet', tone: 'true', core: true, hex: '#603a86' },
  { id: 'heather', name: 'Heather', family: 'violet', tone: 'dusty', core: false, hex: '#6a597e' },
  { id: 'mulberry', name: 'Mulberry', family: 'mulberry', tone: 'deep', core: true, hex: '#542241' },
  { id: 'raspberry', name: 'Raspberry', family: 'mulberry', tone: 'true', core: true, hex: '#7d2d5f' },
  { id: 'mauve', name: 'Mauve', family: 'mulberry', tone: 'dusty', core: false, hex: '#6c465b' },
  { id: 'charcoal', name: 'Charcoal', family: 'neutral', tone: 'deep', core: true, hex: '#2c323b' },
  { id: 'umber', name: 'Umber', family: 'neutral', tone: 'true', core: true, hex: '#5b4130' },
  { id: 'ash', name: 'Ash', family: 'neutral', tone: 'dusty', core: false, hex: '#62594f' },
];
export const CORE_24 = CLOTHS.filter((c) => c.core);
export const clothById = (id: string) => CLOTHS.find((c) => c.id === id);
/** Snap any colour (a sampled cover) to the nearest bookcloth, so every entry's ink comes from the curated set. */
export function nearestCloth(hex: string, set: Cloth[] = CLOTHS): Cloth {
  const lab = (h: string) => { const [L, C, H] = toOklch(h); const r = (H * Math.PI) / 180; return [L, C * Math.cos(r), C * Math.sin(r)]; };
  const [l0, a0, b0] = lab(hex);
  // compare hue and chroma, not lightness: a pale cover and a dark cover of the same hue map to the same family
  let best = set[0], bd = Infinity;
  for (const c of set) { const [l, a, b] = lab(c.hex); const d = (a - a0) ** 2 + (b - b0) ** 2 + 0.02 * (l - l0) ** 2; if (d < bd) { bd = d; best = c; } }
  return best;
}
/** No art and no pick: a stable cloth from the core 24, chosen by the title. */
export function autoCloth(title: string): Cloth {
  let h = 2166136261; for (let i = 0; i < title.length; i++) { h ^= title.charCodeAt(i); h = Math.imul(h, 16777619); }
  return CORE_24[(h >>> 0) % CORE_24.length];
}
